(defparameter *dotimes* 100000)
(defparameter *random-max* 100000000)
(defparameter *sql-command-string* "/dev/shm/sqlite-speed-test/test.sqlite")
(setq *default-pathname-defaults* #p"/dev/shm/sqlite-speed-test/")
(ensure-directories-exist *default-pathname-defaults*)
(defun output-sql(pathname)
  (with-open-file (out pathname :direction :output :if-does-not-exist :create :if-exists :supersede)
    (format out "create table t1(a integer, b int, c text);~%")
    (format out "begin transaction;~%")
    (dotimes (i *dotimes*)
      (format out "insert into t1 values('~D','~D','~:*~R');~%"
	      i (random *random-max*)))
    (format out "commit;~%")))
(time (let* ((path (merge-pathnames "main"))
	     (namestring (namestring path)))
	(output-sql *sql-command-string*)
	(if (probe-file path) (delete-file path))
	(sb-ext:run-program "sqlite3" `(,namestring ,(concatenate 'string  ".read " *sql-command-string* )) :search t)))